  services:
    backend:
      image: 654784951227.dkr.ecr.us-east-1.amazonaws.com/unifit-backend:latest
      container_name: backend
      restart: unless-stopped

      environment:
        SPRING_PROFILES_ACTIVE: prod

        DB_HOST: ${DB_HOST}
        DB_PORT: ${DB_PORT}
        DB_NAME: ${DB_NAME}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}

        KC_CLIENT_ID: ${KC_CLIENT_ID}
        KC_CLIENT_SECRET: ${KC_CLIENT_SECRET}
        KC_REALM: ${KC_REALM}
        
        KC_ISSUER_URI: ${KC_ISSUER_URI}
        KC_AUTH_SERVER_URL: ${KC_AUTH_SERVER_URL}
        BASE_URL: ${BASE_URL}
      expose:
        - "8081"
      depends_on:
        - keycloak
      networks:
        - unifit
    keycloak:
      image: quay.io/keycloak/keycloak:26.2.3
      container_name: keycloak
      restart: unless-stopped
      command: start
      environment:
        KC_DB: mysql
        KC_DB_URL: jdbc:mysql://${DB_HOST}:${DB_PORT}/keycloak
        KC_DB_USERNAME: ${KC_DB_USERNAME}
        KC_DB_PASSWORD: ${KC_DB_PASSWORD}
        KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
        KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
        KC_HTTP_ENABLED: "true"
        KC_HOSTNAME: ${KC_HOSTNAME}
        KC_HOSTNAME_STRICT: "false"
        KC_PROXY_HEADERS: xforwarded
      expose:
        - "8080"
      volumes:
        - keycloak_data:/opt/keycloak/data
      networks:
        - unifit
    nginx:
      image: nginx:1.27-alpine
      container_name: nginx
      restart: unless-stopped
      ports:
        - "80:80"
      volumes:
        - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      depends_on:
        - backend
        - keycloak
      networks:
        - unifit
  volumes:
    keycloak_data:
  networks:
    unifit:
      driver: bridge
