spring.application.name=app_academy

server.port=8081

spring.datasource.url=jdbc:mysql://${DB_HOST}:${DB_PORT}/${DB_NAME}?sslMode=REQUIRED
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

spring.security.oauth2.client.registration.keycloak.client-id=${KC_CLIENT_ID}
spring.security.oauth2.client.registration.keycloak.client-secret=${KC_CLIENT_SECRET}
spring.security.oauth2.client.registration.keycloak.scope=openid
spring.security.oauth2.client.registration.keycloak.authorization-grant-type=authorization_code

spring.security.oauth2.client.provider.keycloak.issuer-uri=${KC_ISSUER_URI}
spring.security.oauth2.client.provider.keycloak.user-name-attribute=preferred_username

base.url=${BASE_URL}

keycloak.auth-server-url=${KC_AUTH_SERVER_URL}
keycloak.realm=${KC_REALM}
keycloak.resource=${KC_CLIENT_ID}
keycloak.credentials.secret=${KC_CLIENT_SECRET}
keycloak.user-login.grant-type=password

spring.main.banner-mode=off

spring.jpa.properties.org.hibernate.envers.store_data_at_delete=true
spring.jpa.properties.org.hibernate.envers.global_with_modified_flag=true